#!/usr/bin/env python3
"""
Example: Customizing the nanopb injector

This example shows how to customize the injector to generate
different types of helper functions based on your needs.
"""

import sys
import os

# Add generator to path
generator_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, generator_dir)

import nanopb_injector

# Inherit from the base CodeInjector
class CustomCodeInjector(nanopb_injector.CodeInjector):
    """
    Custom injector that generates helper functions for
    deep copying and comparison.
    """
    
    def generate_custom_header_code(self):
        """Generate custom function declarations."""
        lines = []
        lines.append("\n" + nanopb_injector.BEGIN_MARKER)
        lines.append("/* Custom helper functions - generated by custom injector */")
        lines.append("")
        
        for message in self.proto_file.messages:
            msg_name = str(message.name)
            
            # Deep copy helper
            lines.append(f"/* Deep copy helper for {msg_name} */")
            lines.append(f"bool {msg_name}_deep_copy(const {msg_name} *src, {msg_name} *dst);")
            lines.append("")
            
            # Comparison helper
            lines.append(f"/* Equality comparison for {msg_name} */")
            lines.append(f"bool {msg_name}_equals(const {msg_name} *a, const {msg_name} *b);")
            lines.append("")
            
            # Size calculation helper
            lines.append(f"/* Calculate encoded size for {msg_name} */")
            lines.append(f"size_t {msg_name}_get_encoded_size(const {msg_name} *msg);")
            lines.append("")
        
        lines.append(nanopb_injector.END_MARKER)
        return '\n'.join(lines)
    
    def generate_custom_source_code(self):
        """Generate custom function implementations."""
        lines = []
        lines.append("\n" + nanopb_injector.BEGIN_MARKER)
        lines.append("/* Custom helper implementations */")
        lines.append("")
        
        for message in self.proto_file.messages:
            msg_name = str(message.name)
            
            # Deep copy implementation
            lines.append(f"bool {msg_name}_deep_copy(const {msg_name} *src, {msg_name} *dst) {{")
            lines.append("    if (!src || !dst) return false;")
            lines.append(f"    *dst = *src;  /* Shallow copy */")
            lines.append("    /* TODO: Deep copy allocated fields */")
            # Note: 'skip_message' is set by nanopb for fields that shouldn't be processed
            # (e.g., OneOf union placeholders). We skip those to avoid duplicates.
            for field in message.fields:
                if hasattr(field, 'name') and not hasattr(field, 'skip_message'):
                    field_name = field.name
                    # Check if this field needs deep copying
                    if hasattr(field, 'allocation') and field.allocation == 'POINTER':
                        lines.append(f"    /* Deep copy pointer field: {field_name} */")
            lines.append("    return true;")
            lines.append("}")
            lines.append("")
            
            # Equality implementation
            lines.append(f"bool {msg_name}_equals(const {msg_name} *a, const {msg_name} *b) {{")
            lines.append("    if (!a || !b) return false;")
            lines.append("    if (a == b) return true;")
            # Note: 'skip_message' is set by nanopb for fields that shouldn't be processed
            # (e.g., OneOf union placeholders). We skip those to avoid duplicates.
            for field in message.fields:
                if hasattr(field, 'name') and not hasattr(field, 'skip_message'):
                    field_name = field.name
                    lines.append(f"    /* Compare field: {field_name} */")
            lines.append("    return true;  /* TODO: Implement field comparison */")
            lines.append("}")
            lines.append("")
            
            # Size calculation implementation
            lines.append(f"size_t {msg_name}_get_encoded_size(const {msg_name} *msg) {{")
            lines.append("    if (!msg) return 0;")
            lines.append("    pb_ostream_t stream = PB_OSTREAM_SIZING;")
            lines.append(f"    if (!pb_encode(&stream, {msg_name}_fields, msg)) return 0;")
            lines.append("    return stream.bytes_written;")
            lines.append("}")
            lines.append("")
        
        lines.append(nanopb_injector.END_MARKER)
        return '\n'.join(lines)

# To use this custom injector, modify nanopb_injector.py:
# Replace:
#   injector = CodeInjector(proto_file, options)
# With:
#   from custom_injector_example import CustomCodeInjector
#   injector = CustomCodeInjector(proto_file, options)

if __name__ == '__main__':
    print(__doc__)
    print("\nThis is an example file showing how to customize the injector.")
    print("To use it, modify nanopb_injector.py to import and use CustomCodeInjector.")
