# Build and run filter_any test suite
# Tests google.protobuf.Any validation with generated validators

Import("env")

# Clone environment to set validation-specific options
test_env = env.Clone()

# Enable validation code generation via NANOPBFLAGS
test_env.Replace(NANOPBFLAGS = "--validate,-x,validate.proto")

# Remove -ansi flag since pb_validate.h requires C99 features (inline)
cflags = str(test_env.get('CFLAGS', ''))
if '-ansi' in cflags:
    cflags = cflags.replace('-ansi', '')
test_env.Replace(CFLAGS = cflags + ' -std=c99 ')

# Prepend the build directory to CPPPATH
test_env.Prepend(CPPPATH = ['.'])

# Build pb_validate.o
test_env.Object("pb_validate.o", "$NANOPB/pb_validate.c")

# Generate nanopb sources for the proto file
pb_files = test_env.NanopbProto("filter_any")
pb_sources = ["filter_any.pb.c"]

# Mark _validate.c as side effect of the proto compilation
validate_c = "filter_any_validate.c"
validate_h = "filter_any_validate.h"
test_env.SideEffect(validate_c, pb_files)
test_env.SideEffect(validate_h, pb_files)
validate_sources = [validate_c]

# Also need to compile google.protobuf.Any
test_env.NanopbProto(["google/protobuf/any", "google/protobuf/any.options"])
pb_sources.append("google/protobuf/any.pb.c")

# All C source files for the test binary
sources = ["test_filter_any.c"] + pb_sources + validate_sources

# Build the test binary
test_prog = test_env.Program(
    sources + [
        "$COMMON/pb_encode.o",
        "$COMMON/pb_decode.o",
        "$COMMON/pb_common.o",
        "pb_validate.o"
    ]
)

# Run the test
test_env.RunTest(test_prog)
