version: '3.8'

services:
  nanopb-dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      # Mount the workspace
      - ..:/workspace:cached
      # Preserve shell history
      - ~/.zsh_history:/root/.zsh_history
      # Preserve git credentials
      - ~/.gitconfig:/root/.gitconfig:ro
      - ~/.ssh:/root/.ssh:ro
    environment:
      - PYTHONPATH=/workspace/generator
    command: sleep infinity
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
