#!/usr/bin/env python3
'''Generate test data for the data_generator_any_decode test case.

Uses generator/nanopb_data_generator.py to build encoded protobuf data for
BaseMessage, which carries a Header and a google.protobuf.Any payload.
The encoded data and the expected field values are written out as a C header
that is consumed by decode_any_message.c.
'''

import os
import sys

def find_repo_root():
    '''Locate the nanopb root, also when running from the scons build dir.'''
    start = os.path.abspath(os.path.dirname(__file__))
    while True:
        if os.path.isfile(os.path.join(start, 'generator', 'nanopb_data_generator.py')):
            return start
        parent = os.path.dirname(start)
        if parent == start:
            raise RuntimeError("could not find nanopb repository root")
        start = parent


REPO_ROOT = find_repo_root()
sys.path.insert(0, REPO_ROOT)

from generator.nanopb_data_generator import DataGenerator

PROTO_DIR = os.path.dirname(os.path.abspath(__file__))
PROTO_FILE = os.path.join(PROTO_DIR, 'base_message.proto')
PAYLOAD_TYPE_URL = 'type.googleapis.com/anydecode.SensorReading'


def c_bytes(name, data):
    values = ', '.join('0x%02x' % byte for byte in data)
    return ('static const uint8_t %s[] = {%s};\n'
            'static const size_t %s_size = %d;\n' % (name, values, name, len(data)))


def wrap_payload(generator, header, payload):
    '''Encode a SensorReading and wrap it in a BaseMessage Any field.'''
    payload_bytes = generator.encode_to_binary('SensorReading', payload)
    return generator.encode_to_binary('BaseMessage', {
        'header': header,
        'message': {'type_url': PAYLOAD_TYPE_URL, 'value': payload_bytes},
    })


def main():
    if len(sys.argv) != 2:
        sys.stderr.write("usage: generate_data.py <output header>\n")
        return 1

    output_path = sys.argv[1]
    generator = DataGenerator(PROTO_FILE, [PROTO_DIR])

    # Valid message: header + Any payload allowed by the any.in rule.
    valid = generator.generate_valid('BaseMessage', seed=1234)
    assert valid['message']['type_url'] == PAYLOAD_TYPE_URL, valid['message']['type_url']
    valid_bytes = generator.encode_to_binary('BaseMessage', valid)

    # Invalid message: Any carries a type_url rejected by the any.in rule.
    bad_any = generator.generate_invalid('BaseMessage', violate_field='message', seed=1234)
    bad_any_bytes = generator.encode_to_binary('BaseMessage', bad_any)

    # Invalid payload: allowed type_url, but the message inside the Any breaks
    # the SensorReading rules.
    bad_value = generator.generate_invalid('SensorReading', violate_field='value', seed=99)
    bad_value_constraint = 'int32.gte' if bad_value['value'] < 10 else 'int32.lte'
    bad_value_msg_bytes = wrap_payload(generator, valid['header'], bad_value)

    # Invalid payload: the string const_value rule of the payload is broken.
    bad_name = generator.generate_invalid('SensorReading', violate_field='sensor_name', seed=7)
    bad_name_msg_bytes = wrap_payload(generator, valid['header'], bad_name)

    header = valid['header']
    payload = generator.registry.get_message_class('anydecode.SensorReading')()
    payload.ParseFromString(valid['message']['value'])

    lines = [
        '/* Automatically generated by generate_data.py, do not edit. */\n',
        '#ifndef ANY_DECODE_DATA_H\n#define ANY_DECODE_DATA_H\n\n',
        '#include <stddef.h>\n#include <stdint.h>\n\n',
        c_bytes('valid_base_message', valid_bytes),
        '\n',
        c_bytes('invalid_any_type_message', bad_any_bytes),
        '\n',
        c_bytes('invalid_payload_message', bad_value_msg_bytes),
        '\n',
        c_bytes('invalid_payload_name_message', bad_name_msg_bytes),
        '\n',
        'static const char expected_payload_constraint[] = "%s";\n\n' % bad_value_constraint,
        c_bytes('expected_message_id', header['message_id'].encode('utf-8')),
        '\n',
        c_bytes('expected_type_url', PAYLOAD_TYPE_URL.encode('utf-8')),
        '\n',
        c_bytes('expected_sensor_name', payload.sensor_name.encode('utf-8')),
        '\n',
        'static const uint32_t expected_version = %dU;\n' % header['version'],
        'static const int32_t expected_sensor_value = %d;\n' % payload.value,
        '\n#endif\n',
    ]

    with open(output_path, 'w') as handle:
        handle.write(''.join(lines))

    return 0


if __name__ == '__main__':
    sys.exit(main())
